plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - "db/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "vendor/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Layout/LineLength:
  Max: 120

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/ContextWording:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Rails/SkipsModelValidations:
  Exclude:
    - "spec/**/*"
  